import "./globals.css";
import Footer from "./layout/footer";
import Header from "./layout/header";
export const metadata = {
  title: "ford-folio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
